#!/bin/bash
# compilesploit by 1N3
# A small script to automatically find and copy an exploit file to the current directory...
#

COLOR1='\033[1m\033[91m'
COLOR2='\033[1m\033[92m'
COLOR3='\033[1m'

function logo {
	echo -e "$COLOR3   ___ _           _           _       _ _   "
	echo -e "$COLOR3  / __(_)_ __   __| |___ _ __ | | ___ (_) |_ "
	echo -e "$COLOR3 / _\ | | '_ \ / _\` / __| '_ \| |/ _ \| | __|"
	echo -e "$COLOR3/ /   | | | | | (_| \__ \ |_) | | (_) | | |_ "
	echo -e "$COLOR3\/    |_|_| |_|\__,_|___/ .__/|_|\___/|_|\__|"
	echo -e "$COLOR3                        |_|                  "
	echo ""
}

if [ -z "$1" ]; 
then
	logo
	echo -e "$COLOR1+ -- --=[compilesploit by 1N3"
	echo -e "$COLOR1+ -- --=[https://crowdshield.com$RESET"
	echo -e "$COLOR1+ -- --=[Usage: compilesploit <filename>"
	echo ""
	echo ""
	exit;
else
	DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
	logo
	echo ""
	echo -e "$COLOR1+ -- --=[compilesploit by 1N3"
        echo -e "$COLOR1+ -- --=[https://crowdshield.com$RESET"
	echo ""
	echo -e "$COLOR1+ -- --=[COMPILING:$COLOR2 $1 $RESET"
	echo ""
	gcc $1 -o $1.out
	echo -e "$COLOR1"
	./$1.out
fi
exit

