#!/bin/bash
# Findsploit by 1N3 @CrowdShield
# https://crowdshield.com
#
# Finsploit is a simple bash script to quickly and easily search both local and online exploit databases.
#

clear

VER='1.6' 
SEARCHSPLOIT_SCRIPT='/usr/share/exploitdb/searchsploit' 
NMAP_SCRIPTS='/usr/share/findsploit/nmap/nmap'
MSF_SEARCH_DIR='/usr/share/findsploit/msf_search'
EXPLOIT_URLS_PATH='/usr/share/findsploit/urls'
BROWSER_CMD='xdg-open' 
# Create this file to override the specified VARS above
if [[ -e ~/.config/findsploit.conf ]]; then
    source ~/.config/findsploit.conf 
fi
VAR1=$1;
VAR2=$2;
VAR3=$3;
VARS="$*"
COLOR1='\033[91m'
COLOR2='\033[1m\033[92m'
COLOR3='\033[1m'
RESET='\e[0m'

function logo {
	echo -e "$COLOR3   ___ _           _           _       _ _   "
	echo -e "$COLOR3  / __(_)_ __   __| |___ _ __ | | ___ (_) |_ "
	echo -e "$COLOR3 / _\ | | '_ \ / _\` / __| '_ \| |/ _ \| | __|"
	echo -e "$COLOR3/ /   | | | | | (_| \__ \ |_) | | (_) | | |_ "
	echo -e "$COLOR3\/    |_|_| |_|\__,_|___/ .__/|_|\___/|_|\__|"
	echo -e "$COLOR3                        |_|                  "
	echo ""
	echo -e "$COLOR1+ -- --=[findsploit v$VER by 1N3"
    echo -e "$COLOR1+ -- --=[https://crowdshield.com$RESET"
	echo ""
}

function update {
	logo
	echo -e "$COLOR1+ -- --=[Checking for updates... $RESET"
	if [[ $(curl -s https://api.github.com/repos/1N3/Findsploit/tags) == "" ]];
	then
    	echo -e "$COLOR1+ -- --=[Error: no active internet connection $RESET"
    	echo ""
    	exit 1
  	fi
  	LATEST_VERSION=$(curl -s https://api.github.com/repos/1N3/Findsploit/tags | grep -Po '"name":.*?[^\\]",'| head -1 | cut -c11-13)
  	if [[ "$LATEST_VERSION" != "$VER" && "$LATEST_VERSION" != "" ]];
  	then
   		echo -e "$COLOR1+ -- --=[Findsploit v$LATEST_VERSION is available to download. $RESET"
   		echo -e "$COLOR1+ -- --=[Do you want to update Findsploit [Y/n]: $RESET"
    	read answer
  		if [[ "$answer" == "Y" || "$answer" == "y" ]] ;
  		then
  			cd  ~ || { echo -e "$COLOR1+ -- --=[Update Failed $RESET" ; exit 1 ; }
			rm -r Findsploit  2> /dev/null
			git clone https://github.com/1N3/Findsploit || { echo -e "$COLOR1+ -- --=[Couldn't download latest version $RESET" ; exit 1; }
			cd Findsploit ||  { echo -e "$COLOR1+ -- --=[Update Failed $RESET" ; exit 1 ;}
			git checkout $LATEST_VERSION 2> /dev/null
			./install.sh
			cd ..
			rm -r Findsploit
  		else
     		exit 1
  		fi
	else
  		echo -e "$COLOR1+ -- --=[Findsploit is already the latest version $RESET"
  		echo ""
	fi
}

if [ -z "$1" ];
then
	logo
	echo -e "$COLOR1+ -- --=[Usage: findsploit windows xp remote, etc."
	echo ""
	echo ""
	exit;
fi

if [[ "$1" == "--update" || "$1" == "-u" ]];
then
	update
	exit
elif [[ "$1" == "auxiliary" ]];
then
	logo
	cat $MSF_SEARCH_DIR/auxiliary
	exit
elif [[ "$1" == "encoders" ]];
then
	logo
	cat $MSF_SEARCH_DIR/encoders
	exit
elif [[ "$1" == "exploits" ]];
then
	logo
	cat $MSF_SEARCH_DIR/exploits
	exit
elif [[ "$1" == "payloads" ]];
then
	logo
	cat $MSF_SEARCH_DIR/payloads
	exit
else
	DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
	logo
	echo -e "$COLOR1+ -- --=[findsploit v$VER by 1N3"
    echo -e "$COLOR1+ -- --=[https://crowdshield.com$RESET"
	echo ""
	echo -e "$COLOR1+ -- --=[SEARCHING: $COLOR2 $VARS $RESET"
	echo ""
	echo -e "$COLOR1+ -- --=[NMAP SCRIPTS$RESET"
	echo ""
	egrep -i "$VAR1" $NMAP_SCRIPTS | egrep -i "$VAR2" --color=auto | egrep -i "$VAR3" --color=auto
	echo ""
	echo -e "$COLOR1+ -- --=[METASPLOIT EXPLOITS$RESET"
	echo ""
	egrep -i "$VAR1" $MSF_SEARCH_DIR/* | egrep -i "$VAR2" --color=auto | egrep -i "$VAR3" --color=auto
	echo ""
	echo -e "$COLOR1+ -- --=[EXPLOITDB EXPLOITS$RESET"
	echo ""
	$SEARCHSPLOIT_SCRIPT $VARS
	echo ""
	echo -e "$COLOR2+ -- --=[Press any key to search online or Ctrl+C to exit...$RESET"
	read test
	$BROWSER_CMD 'https://vuldb.com/?search' 2> /dev/null &
	sleep 5

    OLDIFS=$IFS
IFS="
"
    for raw_url in $(cat $EXPLOIT_URLS_PATH) ; do
        printf -v url "$raw_url" "$VAR1" "$VAR2" "$VAR3"
        $BROWSER_CMD "$url" 2> /dev/null
    done
    IFS=$OLDIFS
fi
exit
