#!/bin/bash
# Findsploit v20150313 by 1N3 @CrowdShield on Twitter
# https://crowdshield.com
#
# ABOUT
# Finsploit is a simple bash script to quickly and easily search both local and online exploit databases.
#
# INSTALLATION
# 1. Extract files to a directory (ie. /pentest/findsploit)
# 2. Set the below params to match your browser and settings
# 3. To run, chmod +x findsploit and ./findsploit iis 5.0 to search
#
# REQUIREMENTS
# This script uses the local exploit-db database for exploits. To install this database locally, use the update.sh script under the exploitdb folder first.
# You will also need to install nmaps script database locally in /usr/share/nmap/scripts/ to locate these scripts locally.
#
# UPDATES
# Check back on https://crowdshield.com for updates to this script.
#
# DISCLAIMER
# CrowdShield takes no responsibility for the use of this script for malicious purposes.
#
clear

SEARCHSPLOIT_SCRIPT='exploitdb/searchsploit' # PATH TO THE EXPLOITDB SEARCH SCRIPT
NMAP_SCRIPTS='nmap' # PATH TO NMAP SCRIPTS 
MSF_SEARCH_DIR='msf_search' # PATH TO THE FILE CONTAINING METASPLOIT EXPLOITS
BROWSER_CMD='iceweasel' # SET THE BROWSER COMMAND HERE
VAR1=$1;
VAR2=$2;
VAR3=$3;
VARS="$1 $2 $3";
COLOR1='\033[91m'
COLOR2='\033[1m\033[92m'
COLOR3='\033[1m'
RESET='\e[0m'

if [ -z "$1" ]; 
then
	echo -e "$COLOR3   ___ _           _           _       _ _   "
	echo -e "$COLOR3  / __(_)_ __   __| |___ _ __ | | ___ (_) |_ "
	echo -e "$COLOR3 / _\ | | '_ \ / _\` / __| '_ \| |/ _ \| | __|"
	echo -e "$COLOR3/ /   | | | | | (_| \__ \ |_) | | (_) | | |_ "
	echo -e "$COLOR3\/    |_|_| |_|\__,_|___/ .__/|_|\___/|_|\__|"
	echo -e "$COLOR3                        |_|                  "
	echo ""
	echo -e "$COLOR1+ -- --=[findsploit by 1N3"
	echo -e "$COLOR1+ -- --=[https://crowdshield.com$RESET"
	echo -e "$COLOR1+ -- --=[Usage: findsploit windows xp remote, etc."
	echo ""
	echo ""
	exit;
else
	echo -e "$COLOR3   ___ _           _           _       _ _   "
	echo -e "$COLOR3  / __(_)_ __   __| |___ _ __ | | ___ (_) |_ "
	echo -e "$COLOR3 / _\ | | '_ \ / _\` / __| '_ \| |/ _ \| | __|"
	echo -e "$COLOR3/ /   | | | | | (_| \__ \ |_) | | (_) | | |_ "
	echo -e "$COLOR3\/    |_|_| |_|\__,_|___/ .__/|_|\___/|_|\__|"
	echo -e "$COLOR3                        |_|                  "
	echo ""
	echo -e "$COLOR1+ -- --=[findsploit by 1N3"
        echo -e "$COLOR1+ -- --=[https://crowdshield.com$RESET"
	echo ""
	echo -e "$COLOR1+ -- --=[SEARCHING: $COLOR2 $VARS $RESET"
	echo ""
	echo -e "$COLOR1+ -- --=[NMAP SCRIPTS$RESET"
	echo ""
	egrep -i "$VAR1" $NMAP_SCRIPTS | egrep -i "$VAR2" --color=auto | egrep -i "$VAR3" --color=auto 
	echo ""
	echo -e "$COLOR1+ -- --=[METASPLOIT EXPLOITS$RESET"
	echo ""
	egrep -i "$VAR1" $MSF_SEARCH_DIR/* | egrep -i "$VAR2" --color=auto | egrep -i "$VAR3" --color=auto 
	echo ""
	echo -e "$COLOR1+ -- --=[EXPLOITDB EXPLOITS$RESET"
	echo ""
	$SEARCHSPLOIT_SCRIPT $VARS 
	echo ""
	echo -e "$COLOR2+ -- --=[Press any key to search online or Ctrl+C to exit...$RESET"
	read test
	$BROWSER_CMD 2> /dev/null &
	sleep 5
	$BROWSER_CMD 'http://www.exploit-db.com/search/?action=search&filter_page=1&filter_description='$VAR1'+'$VAR2'+'$VAR3'&filter_exploit_text=&filter_author=&filter_platform=0&filter_type=0&filter_lang_id=0&filter_port=&filter_osvdb=&filter_cve=' 2>/dev/null
	$BROWSER_CMD 'http://www.exploit-db.com/search/?action=search&filter_page=1&filter_description=&filter_exploit_text='$VAR1'+'$VAR2'+'$VAR3'&filter_author=&filter_platform=0&filter_type=0&filter_lang_id=0&filter_port=&filter_osvdb=&filter_cve=' 2> /dev/null
	$BROWSER_CMD 'https://www.google.ca/search?q='$VAR1'%20'$VAR2'%20'$VAR3'+exploit' 2>/dev/null 
	$BROWSER_CMD 'https://www.google.ca/search?q='$VAR1'%20'$VAR2'%20'$VAR3'+exploit+site:www.securityfocus.com' 2> /dev/null
	$BROWSER_CMD 'https://www.google.ca/search?q='$VAR1'%20'$VAR2'%20'$VAR3'+site:www.1337day.com' 2> /dev/null
	$BROWSER_CMD 'https://www.google.ca/search?q='$VAR1'%20'$VAR2'%20'$VAR3'+site:www.security-database.com' 2> /dev/null
	$BROWSER_CMD 'https://www.google.ca/search?q='$VAR1'%20'$VAR2'%20'$VAR3'+site:packetstormsecurity.com' 2> /dev/null
fi
exit
